apiVersion: apps/v1
kind: Deployment
metadata:
  name: icecream-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: icecream
  template:
    metadata:
      labels:
        app: icecream
    spec:
      containers:
      - name: icecream-web
        image: icecream-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGODB_URI
          value: "mongodb://mongo:27017/icecream"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: icecream-service
spec:
  type: NodePort
  selector:
    app: icecream
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30036